### ISSUE TITLE
Suggestion to apply community i18n based on SWR docs

### ISSUE THREAD

**Issue by guilherssousa** [swc-project/website#172] opened 2022-06-22 14:47 UTC
The SWR website ([vercel/swr-site](https://github.com/vercel/swr-site)) also uses Nextra to seve documentation for users and it accepts 18n translations from the community. It's possible to achieve it by only using default Nextra i18n configuration.

Is there plans to start accepting it?

I'm interested to contributing by translating docs to pt-BR. If it's necessary, I'm willing to prepare the field for community docs i18n.

**Comment by kwonoj** [comment] 2022-06-22 15:09
I believe this is dupe of https://github.com/swc-project/swc/discussions/4966. As said, we are not restrict any userland / community effort but do not have any policies or immediate plan to promot it to be included in official docs page.

**Closed** 2022-06-22 16:43 UTC
